cursor #e2e2e5
cursor_text_color #c2c7ce

foreground            #e2e2e5
background            #111416
selection_foreground  #23323f
selection_background  #b8c8da
url_color             #a0cbf3

color0   #111416
color1   #ff729d
color2   #79f389
color3   #fff772
color4   #88b9e6
color5   #2a4e70
color6   #a0cbf3
color7   #eff7ff
color8   #92989d
color9   #ff9fbc
color10  #a5ffb1
color11  #fffaa5
color12  #b4dbff
color13  #c2e1ff
color14  #d7ecff
color15  #f8fbff
