cursor #e4e2e2
cursor_text_color #c3c7ca

foreground            #e4e2e2
background            #131314
selection_foreground  #2d3133
selection_background  #c3c7ca
url_color             #bcc8cf

color0   #131314
color1   #ee6b94
color2   #67cf73
color3   #fff672
color4   #aebcc4
color5   #4f595f
color6   #bcc8cf
color7   #ccd4d9
color8   #7c8286
color9   #ff9fbd
color10  #a1f8ab
color11  #fff9a5
color12  #d1dde3
color13  #eef8ff
color14  #f4fbff
color15  #f8fcff
