cursor #f6ddda
cursor_text_color #e0bfbb

foreground            #f6ddda
background            #1c100f
selection_foreground  #571d1a
selection_background  #ffb4ac
url_color             #ffb4ac

color0   #1c100f
color1   #ff7472
color2   #9aff7f
color3   #ffe472
color4   #f29c93
color5   #76362f
color6   #ffb4ac
color7   #fff1ef
color8   #a59a99
color9   #ffa09f
color10  #b8ffa5
color11  #ffeea5
color12  #ffbfb8
color13  #ffcac4
color14  #ffddd9
color15  #fff9f8
