color0 #101414
color1 #ffb4ab
color2 #4edad3
color3 #b0ccc9
color4 #b0c9e7
color5 #4edad3
color6 #b0ccc9
color7 #e0e3e2
color8 #889391
color9 #ffb4ab
color10 #4edad3
color11 #b0ccc9
color12 #b0c9e7
color13 #4edad3
color14 #b0ccc9
color15 #e0e3e2

cursor                #e0e3e2
cursor_text_color     #101414
background            #101414
foreground            #e0e3e2
selection_foreground  #bec9c7
selection_background  #3f4948
active_border_color   #4edad3
inactive_border_color #3f4948
url_color             #4edad3

active_tab_foreground   #003735
active_tab_background   #4edad3
inactive_tab_foreground #bec9c7
inactive_tab_background #3f4948
cursor_trail_color      #bec9c7
