color0 #141316
color1 #ffb4ab
color2 #d3bbff
color3 #cdc2db
color4 #f0b7c5
color5 #d3bbff
color6 #cdc2db
color7 #e6e1e6
color8 #948f99
color9 #ffb4ab
color10 #d3bbff
color11 #cdc2db
color12 #f0b7c5
color13 #d3bbff
color14 #cdc2db
color15 #e6e1e6

cursor                #e6e1e6
cursor_text_color     #141316
background            #141316
foreground            #e6e1e6
selection_foreground  #cbc4cf
selection_background  #49454e
active_border_color   #d3bbff
inactive_border_color #49454e
url_color             #d3bbff

active_tab_foreground   #3b1d70
active_tab_background   #d3bbff
inactive_tab_foreground #cbc4cf
inactive_tab_background #49454e
cursor_trail_color      #cbc4cf
