color0 #51443a
color1 #ffb4ab
color2 #ffcea7
color3 #e4c0a4
color4 #d8dd8f
color5 #fcb880
color6 #e4c0a4
color7 #ece0d9
color8 #9e8e82
color9 #ffb4ab
color10 #ffcea7
color11 #e4c0a4
color12 #d8dd8f
color13 #fcb880
color14 #e4c0a4
color15 #ece0d9

cursor                #ece0d9
cursor_text_color     #000000
background            #000000
foreground            #ece0d9
selection_foreground  #d6c3b6
selection_background  #51443a
active_border_color   #ffcea7
inactive_border_color #43372d
url_color             #ffcea7

active_tab_foreground   #4c2700
active_tab_background   #ffcea7
inactive_tab_foreground #d6c3b6
inactive_tab_background #43372d
cursor_trail_color      #d6c3b6
